baseURL      = 'https://vitor-mafra.github.io/about_me/'
title        = "me"
languageCode = "en-us"
theme        = "hello-friend-ng"

buildDrafts  = false
buildFuture  = true
buildExpired = false

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[params]
    Author = "Vitor Mafra"
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "data scientist, researcher. curious."

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true

    # Show a global language switcher in the navigation bar
    enableGlobalLanguageMenu = false

    # Metadata mostly used in document's head
    description = "about_me"
    keywords = "homepage"
    images = [""]

    enableThemeToggle = true

[params.portrait]
    path     = "/about_me/cv/images/profile_picture.jpeg"
    alt      = "A picture of me. I am smiling, with a beard and curly hair, wearing a light National Geographic cap and a green shirt, standing outdoors against a greenish-yellow background with soft sunlight."
    maxWidth = "205px"

[params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

# Social icons
[[params.social]]
    name = "X"
    url  = "https://twitter.com/ovitormafra"

[[params.social]]
    name = "github"
    url  = "https://github.com/vitor-mafra"

[[params.social]]
    name = "leetcode"
    url  = "https://leetcode.com/u/vitoromafra/"

[[params.social]]
    name = "kaggle"
    url  = "https://www.kaggle.com/vitormafra"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/vitor-mafra/"

[[params.social]]
    name = "email"
    url  = "mailto:vitor.mafra@dcc.ufmg.br"




[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Vitor Mafra"
        keywords = ""
        readOtherPosts = "Read other posts"

    [languages.en.params]
        #subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
        logoText = "vitor_mafra"
        logoHomeLink = "/about_me/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

    # And you can even create generic menu
    [[menu.main]]
        identifier = "blog"
        name       = "blog"
        url        = "/blog/"

    [[menu.main]]
        identifier = "about_me"
        name       = "about_me"
        url        = '/about_me/'

    [[menu.main]]
        identifier = "cv"
        name       = "cv"
        url        = "/cv/cv_vitor_mafra.pdf"

    [[menu.main]]
        identifier = "on media"
        name       = "on_media"
        url        = '/on_media/'

    [[menu.main]]
        identifier = "publications"
        name       = "publications"
        url        = "https://scholar.google.com.br/citations?user=j8YQQVYAAAAJ&hl=pt-BR&oi=ao"

    [[menu.main]]
        identifier = "running"
        name       = "running"
        url        = '/running/'


    [markup.goldmark.renderer]
        unsafe = true
